### ISSUE TITLE
HostMacroService

### ISSUE THREAD

**Issue by nail4** [HenriqueCaires/ZabbixApi#16]
Hi!
```
ZabbixApi.Services.HostMacroService macro_s = new ZabbixApi.Services.HostMacroService(context);
IEnumerable<ZabbixApi.Entities.HostMacro> macros = macro_s.Get(new { hostid = host.Id });
```
Filter seems to be ignored. Get returns all macros found on Zabbix Server not just for selected host.Id

**Comment by dominicx** [comment]
the object for new { hostid = host.Id }) is HostMacroService , it is not filter
try it:
var filter = new Dictionary<string, object>();
filter.Add("hostids", ids);
macro_sGet(filter: filter);

**Comment by nail4** [comment]
Thx!
This worked!
