### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by vfabregat** [HenriqueCaires/ZabbixApi#21]
Hi, is in your plans add async support for the API?

**Comment by HenriqueCaires** [comment]
Hi, it is. But lately I haven't had much time to do it.

**Comment by vfabregat** [comment]
Nice, and how do planned to implement?

Do you want to keep the support for syncronous and async operations or just Async operations will be maintaned (http://stackoverflow.com/questions/14870478/write-a-well-designed-async-non-async-api)

And another question, how do you think that will be implemented the thread-safe in the async context? (http://stackoverflow.com/questions/32102888/how-do-i-keep-my-async-method-thread-safe)

Maybe I can help you with this, for that my questions.
