### ISSUE TITLE
can the output param work?

### ISSUE THREAD

**Issue by ICE2017** [HenriqueCaires/ZabbixApi#22]
can the output param work ?  
`                 IEnumerable<Item> items=itemService.Get(null, null, new Dictionary<string, object> { 
                    {"hostids",hostId},
                    {"output",new String[]{"itemid","name","lastvalue","lastclock"}}
                });`

**Comment by HenriqueCaires** [comment]
It should work, isn't it working for you?

**Comment by onlyoneice** [comment]
en  when i use outpu params,the return IEnumerable does not work, i used zabbix 3.0

**Comment by HenriqueCaires** [comment]
Sorry for taking so long to reply.

I actually didn't do any test on 3.0, I will try 3.0 and fix as soon as possible.
